name: General
description: Anything about the project that is not a question or an idea
title: "[General]: "
body:
  - type: textarea
    id: topic
    attributes:
      label: Topic
      description: What do you want to talk about?
    validations:
      required: true
  - type: checkboxes
    id: checks
    attributes:
      label: Checks
      options:
        - label: This is not a bug report (those go to Issues) and not a usage question (those go to Q&A)
          required: true
